import React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import '@/styles/icons.css'

import { ThemeProvider } from '@/context/ThemeContext'

import Sidebar from '../containers/Sidebar/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <ThemeProvider>
        <body>
          <div className='main-dashboard'>
            <Sidebar />
            {children}
          </div>
        </body>
      </ThemeProvider>
    </html>
  )
}
